### ISSUE TITLE
Mixing rackunit and quickcheck

### ISSUE THREAD

**Issue by eu90h** [ifigueroap/racket-quickcheck#8]
I'd like to be able to write some tests using quickcheck and others using rackunit (I know this is probably silly). 

However if I try `(require rackunit quickcheck)` I get an error
`module: identifier already imported from a different source in:
  check
  quickcheck
  rackunit`

Is there any way to use both?

**Comment by ifigueroap** [comment]
Hi eu90h, 

In Racket you have several options to disambiguate identifiers. The first option is to add a prefix to *all* identifiers from quickcheck, using the [```prefix-in```](http://docs.racket-lang.org/reference/require.html#%28form._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._prefix-in%29%29) form for module requirement.

```(require rackunit (prefix-in qc- quickcheck))```

This adds the ```qc-``` prefix to every export in quickcheck. Therefore you would have functions ```check```, from rackunit, and ```qc-check``` from quickcheck. You'd also be forced to use ```qc-quickcheck``` instead of just ```quickcheck```.

The other option is to just rename the conflicting identifier, in this case ```check```. To do this you need to use the [```rename-in```](http://docs.racket-lang.org/reference/require.html#%28form._%28%28lib._racket%2Fprivate%2Fbase..rkt%29._rename-in%29%29) form:

```(require rackunit (rename-in quickcheck (check qc-check)))```

Which means you only need to use ```qc-check``` but you can use ```quickcheck``` and others directly.

Of course, you can do the renames the other way, ie. ru-check, or as you like ;-)

Hope this helps!

**Comment by eu90h** [comment]
Thank you very much. I clearly still have a lot to learn about Racket :P.

**Comment by ifigueroap** [comment]
No problem, do not hesitate to ask for further help ;)

**Comment by ifigueroap** [comment]
@eu90h, we recently modified the library so there is no conflict. Now all quickcheck-related functions  start with `quickcheck`. Furthermore, we provide a small integration between quickcheck and RackUnit. Please refer to commit 4cfecbb1b3cdc07c28bca47f3512aecf11eb15ab for the specific details.

**Comment by eu90h** [comment]
Thanks, appreciate the update. Keep up the good work!
